Quiz/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'Quiz'

urlpatterns = [
    path('quiz', views.fetch_data, name='quiz'), 
    path('submit/', views.submit_answers, name='submit_answers'),
    path('result/', views.result, name='result'),
    path('login/', auth_views.LoginView.as_view(template_name='Quiz/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', views.register, name='register'),
    path('', views.quiz_config, name='quiz_config'),
]


    

Quiz_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Quiz.urls')),
]

Quiz/models.py
from django.db import models

class LeaderboardEntry(models.Model):
    user_name = models.CharField(max_length=100)
    score = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-score', 'timestamp']

    def __str__(self):
        return f"{self.user_name} - {self.score}"

Quiz/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']



class QuizConfigForm(forms.Form):
    CATEGORY_CHOICES = [
        ('9', 'General Knowledge'),
        ('10', 'Entertainment: Books'),
        ('11', 'Entertainment: Film'),
        ('12', 'Entertainment: Music'),
        ('13', 'Entertainment: Musicals & Theatres'),
        ('14', 'Entertainment: Television'),
        ('15', 'Entertainment: Video Games'),
        ('16', 'Entertainment: Board Games'),
        ('17', 'Science & Nature'),
        ('18', 'Science: Computers'),
        ('19', 'Science: Mathematics'),
        ('20', 'Mythology'),
        ('21', 'Sports'),
        ('22', 'Geography'),
        ('23', 'History'),
        ('24', 'Politics'),
        ('25', 'Art'),
        ('26', 'Celebrities'),
        ('27', 'Animals'),
        ('28', 'Vehicles'),
        ('29', 'Entertainment: Comics'),
        ('30', 'Science: Gadgets'),
        ('31', 'Entertainment: Japanese Anime & Manga'),
        ('32', 'Entertainment: Cartoon & Animations'),
    ]
    DIFFICULTY_CHOICES = [
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    ]
    TYPE_CHOICES = [
        ('multiple', 'Multiple Choice'),
        ('boolean', 'True/False'),
    ]

    category = forms.ChoiceField(choices=CATEGORY_CHOICES, label='Category')
    difficulty = forms.ChoiceField(choices=DIFFICULTY_CHOICES, label='Difficulty')
    question_type = forms.ChoiceField(choices=TYPE_CHOICES, label='Type')

Quiz/views.py
import requests
import random
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from django.contrib.auth import login
from django.views.decorators.csrf import csrf_exempt
from . models import LeaderboardEntry
from . forms import RegistrationForm
from .forms import QuizConfigForm

# Create your views here.

def generate_api_url(session_data):
    base_url = 'https://opentdb.com/api.php?amount=10'
    category = session_data.get('category')
    difficulty = session_data.get('difficulty')
    question_type = session_data.get('question_type')

    if category:
        base_url += f'&category={category}'
    if difficulty:
        base_url += f'&difficulty={difficulty}'
    if question_type:
        base_url += f'&type={question_type}'

    return base_url


@login_required
def fetch_data(request):
    if 'quiz_config' not in request.session:
        return redirect('Quiz:quiz_config')

    quiz_config = request.session['quiz_config']
    del request.session['quiz_config']
    url = generate_api_url(quiz_config)
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()

        if len(data['results']) < 10:
            return render(request, 'Quiz/not_enough_questions.html', {'message': "Please change quiz criteria. There are not enough questions available."})

        for question in data['results']:
            answers = question['incorrect_answers']
            answers.append(question['correct_answer'])
            random.shuffle(answers)
            question['mixed_answers'] = answers

        request.session['questions'] = data['results']

        return render(request, 'Quiz/data.html', {'data': data})
    else:
        return render(request, 'Quiz/data.html', {'data': None})
    



@csrf_exempt    
@login_required
def submit_answers(request):
    if request.method == 'POST':
        points = 0
        for key, value in request.POST.items():
            if key.startswith('question_'):
                question_index = int(key.split('_')[1]) - 1
                selected_answer = value

                question_data = request.session['questions'][question_index]
                correct_answer = question_data['correct_answer']
                difficulty = question_data['difficulty']

                if selected_answer == correct_answer:
                    if difficulty == 'easy':
                        points += 1
                    elif difficulty == 'medium':
                        points += 2
                    elif difficulty == 'hard':
                        points += 3

        request.session['points'] = points
        return redirect('Quiz:result')
    else:
        return redirect('Quiz:fetch_data')
    

@login_required
def result(request):
    if 'points' not in request.session:
        return redirect('Quiz:quiz')

    points = request.session['points']
    del request.session['points']

    new_entry = LeaderboardEntry(user_name=request.user, score=points)
    new_entry.save()

    leaderboard = LeaderboardEntry.objects.all()[:10]

    return render(request, 'Quiz/result.html', {'points': points, 'leaderboard': leaderboard})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('Quiz:quiz')
    else:
        form = RegistrationForm()
    return render(request, 'Quiz/register.html', {'form': form})


@login_required
def quiz_config(request):
    if request.method == 'POST':
        form = QuizConfigForm(request.POST)
        if form.is_valid():
            category = form.cleaned_data['category']
            difficulty = form.cleaned_data['difficulty']
            question_type = form.cleaned_data['question_type']

            request.session['quiz_config'] = {
                'category': category,
                'difficulty': difficulty,
                'question_type': question_type,
            }
            return redirect('Quiz:quiz')
    else:
        form = QuizConfigForm()

    return render(request, 'Quiz/quiz_config.html', {'form': form})

Quiz/templates/Quiz/data.html
{% extends 'Quiz/main.html' %}

{% block title %}My Quiz{% endblock %}

{% block content %}
    <div class="main">
    {% if data %}
        <h1>My Quiz:)</h1>
        <h2>
            <strong>Category:</strong> {{ data.results.0.category }}<br>
            <strong>Difficulty:</strong> {{ data.results.0.difficulty }}
        </h2>
        <form method="post" action="{% url 'Quiz:submit_answers' %}">
            <ul>    
            {% csrf_token %}
            {% for question in data.results %}
                <li>
                    <strong>Question:</strong> {{ question.question|safe }}<br>
                    {% for answer in question.mixed_answers %}
                        <input type="radio" name="question_{{ forloop.parentloop.counter }}" value="{{ answer|escape }}" id="answer_{{ forloop.parentloop.counter }}_{{ forloop.counter }}">
                        <label for="answer_{{ forloop.parentloop.counter }}_{{ forloop.counter }}">{{ answer|safe }}</label><br>
                    {% endfor %}
                </li>
            {% endfor %}
            </ul>
        <button type="submit">Submit</button>
        </form>
    {% else %}
        <h1>Error fetching trivia data</h1>
    {% endif %}
    </div>
{% endblock %}

Quiz/templates/Quiz/login.html
{% extends "Quiz/main.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="main">
    <div class="container">
        <h1>Login</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>
{% endblock %}

Quiz/templates/Quiz/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Quiz/css/styles.css' %}">
    <title>{% block title %}Quiz{% endblock %}</title>
</head>
<body>
    <nav>
        <div class="nav-container">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'Quiz:logout' %}">Logout</a>
            {% else %}
                <a class="nav-link" href="{% url 'Quiz:register' %}">Register</a>
                <a class="nav-link" href="{% url 'Quiz:login' %}">Login</a>
            {% endif %}
        </div>
    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

Quiz/templates/Quiz/not_enough_questions.html
{% extends 'Quiz/main.html' %}

{% block content %}
<div class = "main">
    <h2>{{ message }}</h2>
    <p><a href="{% url 'Quiz:quiz_config' %}">Go back to quiz configuration</a></p>
</div>
{% endblock %}

Quiz/templates/Quiz/quiz_config.html
{% extends "Quiz/main.html" %}

{% block title %}Quiz Configuration{% endblock %}

{% block content %}
<div class = "main">
    <div class="container">
        <h1>Quiz Configuration</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Start Quiz</button>
        </form>
    </div>
</div>
{% endblock %}

Quiz/templates/Quiz/register.html
{% extends "Quiz/main.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<div class = "main">
    <div class="container">
        <h1>Register</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>
{% endblock %}

Quiz/templates/Quiz/result.html
{% extends "Quiz/main.html" %}

{% block title %}Quiz Results{% endblock %}

{% block content %}
<div class = "main">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>Your Score: {{ points }}</h1>
            </div>
            <div class="col-md-6">
                <h1>Leaderboard</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Rank</th>
                            <th scope="col">Name</th>
                            <th scope="col">Score</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entry in leaderboard %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ entry.user_name }}</td>
                                <td>{{ entry.score }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}